
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 19 10:52:10 CST 2018
//----------------------------------------------------

package CHTML.Auxiliares;

/** CUP generated class containing symbol constants. */
public class Symb {
  /* terminals */
  public static final int opentag = 9;
  public static final int id = 4;
  public static final int coma = 13;
  public static final int cadena = 14;
  public static final int ancho = 7;
  public static final int pcoma = 12;
  public static final int salida = 15;
  public static final int EOF = 0;
  public static final int texto = 2;
  public static final int closetag = 10;
  public static final int finTexto = 3;
  public static final int error = 1;
  public static final int alineado = 8;
  public static final int grupo = 5;
  public static final int igual = 11;
  public static final int alto = 6;
}

