
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 25 03:09:38 CST 2018
//----------------------------------------------------

package CJS;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int dimv = 2;
  public static final int imprimir = 45;
  public static final int mod = 12;
  public static final int detener = 44;
  public static final int coma = 6;
  public static final int dism = 14;
  public static final int divi = 10;
  public static final int tTrue = 18;
  public static final int conteo = 34;
  public static final int si = 37;
  public static final int mientras = 43;
  public static final int igualacion = 22;
  public static final int iden = 4;
  public static final int defecto = 41;
  public static final int tFalse = 19;
  public static final int aum = 13;
  public static final int menos = 8;
  public static final int menor = 25;
  public static final int EOF = 0;
  public static final int cadena2 = 17;
  public static final int cadena1 = 16;
  public static final int mas = 7;
  public static final int para = 42;
  public static final int error = 1;
  public static final int pcoma = 3;
  public static final int mayor = 24;
  public static final int or = 29;
  public static final int menorigual = 26;
  public static final int por = 9;
  public static final int mensaje = 47;
  public static final int punto = 36;
  public static final int funcion = 46;
  public static final int oKey = 31;
  public static final int caso = 40;
  public static final int cKey = 32;
  public static final int elev = 11;
  public static final int mayorigual = 27;
  public static final int numeric = 15;
  public static final int diferente = 23;
  public static final int and = 28;
  public static final int not = 30;
  public static final int dosP = 5;
  public static final int atexto = 35;
  public static final int retornar = 33;
  public static final int selecciona = 39;
  public static final int sino = 38;
  public static final int oParent = 20;
  public static final int cParent = 21;
}

