
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 03 01:47:17 CST 2018
//----------------------------------------------------

package CJS;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int dimv = 2;
  public static final int imprimir = 40;
  public static final int mod = 11;
  public static final int detener = 39;
  public static final int coma = 5;
  public static final int dism = 13;
  public static final int setElemento = 44;
  public static final int divi = 9;
  public static final int tTrue = 50;
  public static final int conteo = 29;
  public static final int si = 32;
  public static final int mientras = 38;
  public static final int igualacion = 16;
  public static final int iden = 46;
  public static final int tFalse = 51;
  public static final int observador = 45;
  public static final int defecto = 36;
  public static final int aum = 12;
  public static final int menos = 7;
  public static final int menor = 19;
  public static final int cadena2 = 49;
  public static final int EOF = 0;
  public static final int cadena1 = 48;
  public static final int mas = 6;
  public static final int para = 37;
  public static final int error = 1;
  public static final int pcoma = 3;
  public static final int mayor = 18;
  public static final int or = 23;
  public static final int menorigual = 20;
  public static final int por = 8;
  public static final int mensaje = 42;
  public static final int punto = 31;
  public static final int funcion = 41;
  public static final int oKey = 25;
  public static final int obtener = 28;
  public static final int caso = 35;
  public static final int cKey = 26;
  public static final int elev = 10;
  public static final int mayorigual = 21;
  public static final int numeric = 47;
  public static final int documento = 43;
  public static final int diferente = 17;
  public static final int and = 22;
  public static final int not = 24;
  public static final int dosP = 4;
  public static final int atexto = 30;
  public static final int retornar = 27;
  public static final int selecciona = 34;
  public static final int oParent = 14;
  public static final int cParent = 15;
  public static final int sino = 33;
}

