
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 07 02:02:19 CST 2018
//----------------------------------------------------

package CHTML;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int palabra = 33;
  public static final int ancho = 38;
  public static final int finCuerpo = 14;
  public static final int finSpinner = 46;
  public static final int finPanel = 23;
  public static final int fondo = 31;
  public static final int closetag = 3;
  public static final int imagen = 24;
  public static final int finOpcion = 59;
  public static final int finEnlace = 27;
  public static final int tTexA = 53;
  public static final int coma = 6;
  public static final int igual = 4;
  public static final int finTitulo = 21;
  public static final int finFil_t = 48;
  public static final int finTabla = 44;
  public static final int finChtml = 10;
  public static final int caja_texto = 54;
  public static final int saltoFin = 28;
  public static final int finEncabezado = 12;
  public static final int alto = 37;
  public static final int texto_a = 29;
  public static final int panel = 22;
  public static final int grupo = 36;
  public static final int finCt = 52;
  public static final int alineado = 39;
  public static final int ruta = 32;
  public static final int tTexto = 8;
  public static final int opentag = 2;
  public static final int ccss = 18;
  public static final int fil_t = 47;
  public static final int tabla = 43;
  public static final int chtml = 9;
  public static final int ct = 51;
  public static final int especiales = 15;
  public static final int EOF = 0;
  public static final int finCjs = 17;
  public static final int error = 1;
  public static final int pcoma = 5;
  public static final int finCb = 50;
  public static final int finImagen = 25;
  public static final int finTexto = 63;
  public static final int finTextoA = 30;
  public static final int entero = 61;
  public static final int valor = 60;
  public static final int cuerpo = 13;
  public static final int spinner = 45;
  public static final int finCcss = 19;
  public static final int click = 34;
  public static final int cb = 49;
  public static final int id = 35;
  public static final int finCaja_texto = 55;
  public static final int finBoton = 42;
  public static final int opcion = 58;
  public static final int cjs = 16;
  public static final int enlace = 26;
  public static final int titulo = 20;
  public static final int texto = 62;
  public static final int caja = 56;
  public static final int path = 40;
  public static final int encabezado = 11;
  public static final int boton = 41;
  public static final int cadena = 7;
  public static final int finCaja = 57;
}

