
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 18:21:12 CST 2018
//----------------------------------------------------

package CHTML;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int palabra = 30;
  public static final int ancho = 35;
  public static final int finCuerpo = 14;
  public static final int finSpinner = 43;
  public static final int finPanel = 22;
  public static final int fondo = 28;
  public static final int closetag = 3;
  public static final int imagen = 23;
  public static final int finOpcion = 56;
  public static final int finEnlace = 26;
  public static final int tTexA = 50;
  public static final int coma = 6;
  public static final int igual = 4;
  public static final int finTitulo = 20;
  public static final int finFil_t = 45;
  public static final int finTabla = 41;
  public static final int finChtml = 10;
  public static final int caja_texto = 51;
  public static final int saltoFin = 27;
  public static final int finEncabezado = 12;
  public static final int alto = 34;
  public static final int panel = 21;
  public static final int grupo = 33;
  public static final int finCt = 49;
  public static final int alineado = 36;
  public static final int ruta = 29;
  public static final int tTexto = 8;
  public static final int opentag = 2;
  public static final int ccss = 17;
  public static final int fil_t = 44;
  public static final int tabla = 40;
  public static final int chtml = 9;
  public static final int ct = 48;
  public static final int EOF = 0;
  public static final int finCjs = 16;
  public static final int error = 1;
  public static final int pcoma = 5;
  public static final int finCb = 47;
  public static final int finImagen = 24;
  public static final int entero = 58;
  public static final int valor = 57;
  public static final int cuerpo = 13;
  public static final int spinner = 42;
  public static final int finCcss = 18;
  public static final int click = 31;
  public static final int cb = 46;
  public static final int id = 32;
  public static final int finCaja_texto = 52;
  public static final int finBoton = 39;
  public static final int opcion = 55;
  public static final int cjs = 15;
  public static final int enlace = 25;
  public static final int titulo = 19;
  public static final int caja = 53;
  public static final int path = 37;
  public static final int encabezado = 11;
  public static final int boton = 38;
  public static final int cadena = 7;
  public static final int finCaja = 54;
}

