
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 20 01:12:54 CST 2018
//----------------------------------------------------

package CHTML;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int palabra = 29;
  public static final int finCuerpo = 14;
  public static final int ancho = 34;
  public static final int finPanel = 22;
  public static final int fondo = 27;
  public static final int closetag = 3;
  public static final int imagen = 23;
  public static final int finEnlace = 26;
  public static final int tTexA = 47;
  public static final int coma = 6;
  public static final int igual = 4;
  public static final int finTitulo = 20;
  public static final int finFil_t = 42;
  public static final int finTabla = 40;
  public static final int finChtml = 10;
  public static final int caja_texto = 48;
  public static final int finEncabezado = 12;
  public static final int alto = 33;
  public static final int panel = 21;
  public static final int grupo = 32;
  public static final int finCt = 46;
  public static final int alineado = 35;
  public static final int ruta = 28;
  public static final int tTexto = 8;
  public static final int opentag = 2;
  public static final int ccss = 17;
  public static final int fil_t = 41;
  public static final int tabla = 39;
  public static final int chtml = 9;
  public static final int ct = 45;
  public static final int EOF = 0;
  public static final int finCjs = 16;
  public static final int error = 1;
  public static final int pcoma = 5;
  public static final int finCb = 44;
  public static final int finImagen = 24;
  public static final int cuerpo = 13;
  public static final int finCcss = 18;
  public static final int click = 30;
  public static final int cb = 43;
  public static final int id = 31;
  public static final int finCaja_texto = 49;
  public static final int finBoton = 38;
  public static final int cjs = 15;
  public static final int enlace = 25;
  public static final int titulo = 19;
  public static final int path = 36;
  public static final int encabezado = 11;
  public static final int boton = 37;
  public static final int cadena = 7;
}

