/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author richard
 */
import AST.*;
import CHTML.*;
import java.io.FileReader;
import javax.swing.JOptionPane;
import CHTML_EXEC.Interprete_CHTML;
import Objetos.Panel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.security.Principal;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.ScrollPaneLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
public class Pestania extends javax.swing.JPanel {

    /**
     * Creates new form Pestania
     */
    
    JTabbedPane padre;
    int index;
    JPanel panelPrincipal;
    int alto = 10000, largo = 2000;
    
    public Pestania() {
        initComponents();
        
    }
    
    
    public Pestania(JTabbedPane padre, int index)
    {
        initComponents();
        this.padre = padre;
        this.index = index;
        this.ErrorTable.setVisible(false);
        
    }
    
    public Pestania(JTabbedPane padre, int index, int largo, int alto)
    {
        initComponents();
        this.padre = padre;
        this.index = index;
        this.ErrorTable.setVisible(false);
        if(largo > this.largo)
        {
            this.largo = largo;
        }
        if(alto > this.alto)
        {
            this.alto = alto;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        URL_Search = new javax.swing.JTextField();
        btnExec = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MainPageTab = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ErrorConsole = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ErrorTable = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnBack.setIcon(new javax.swing.ImageIcon("/home/richard/Documents/Universidad/Compiladores 2/USAC_WEB/IMGS/if_arrow_full_left_103292.png")); // NOI18N
        btnBack.setMaximumSize(new java.awt.Dimension(50, 50));
        btnBack.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(btnBack);

        btnForward.setIcon(new javax.swing.ImageIcon("/home/richard/Documents/Universidad/Compiladores 2/USAC_WEB/IMGS/if_arrow_full_right_103295.png")); // NOI18N
        btnForward.setMaximumSize(new java.awt.Dimension(50, 50));
        btnForward.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(btnForward);

        btnRefresh.setIcon(new javax.swing.ImageIcon("/home/richard/Documents/Universidad/Compiladores 2/USAC_WEB/IMGS/if_refresh22_216527.png")); // NOI18N
        btnRefresh.setMaximumSize(new java.awt.Dimension(50, 50));
        btnRefresh.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(btnRefresh);

        URL_Search.setFont(new java.awt.Font("Ubuntu Condensed", 0, 24)); // NOI18N
        URL_Search.setToolTipText("URL...");
        jPanel1.add(URL_Search);

        btnExec.setIcon(new javax.swing.ImageIcon("/home/richard/Documents/Universidad/Compiladores 2/USAC_WEB/IMGS/if_11_Search_106236.png")); // NOI18N
        btnExec.setMaximumSize(new java.awt.Dimension(50, 50));
        btnExec.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecActionPerformed(evt);
            }
        });
        jPanel1.add(btnExec);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("USAC WEB");
        jPanel2.add(jLabel1);

        ErrorConsole.setAutoscrolls(true);
        ErrorConsole.setPreferredSize(new java.awt.Dimension(1000, 2000));

        ErrorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(ErrorTable);

        javax.swing.GroupLayout ErrorConsoleLayout = new javax.swing.GroupLayout(ErrorConsole);
        ErrorConsole.setLayout(ErrorConsoleLayout);
        ErrorConsoleLayout.setHorizontalGroup(
            ErrorConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        ErrorConsoleLayout.setVerticalGroup(
            ErrorConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorConsoleLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1509, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(ErrorConsole);

        MainPageTab.addTab("Consola de Errores", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPageTab, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPageTab, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecActionPerformed
        // BOTON QUE INICIA LA INTERPTRETACION DEL CHTML
        ASTNodo raizCHTML = null;
        try 
        {
            panelPrincipal = new JPanel(new FlowLayout(FlowLayout.CENTER));
            panelPrincipal.setPreferredSize(new Dimension(largo, alto));
            LexCHTML lex = new LexCHTML(new FileReader(URL_Search.getText()));
            parser p = new parser(lex);
            p.parse();
            if(parser.raiz!=null)
            {
                raizCHTML = parser.raiz;
                //EJECUTA LA ACCION DE PARSEAR EL CHTML
                System.out.println(raizCHTML.graficaAST(raizCHTML));
                Interprete_CHTML nuevo = new Interprete_CHTML(raizCHTML, panelPrincipal, padre, index);
                nuevo.InicioCHTML();
                ErrorModel modelo = new ErrorModel(nuevo.getErrores());
                ErrorTable.setModel(modelo);
                ErrorTable.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Se encontraron muchos errores en el archivo, revisa la sintaxis...");
            }
            JScrollPane scroll = new JScrollPane(panelPrincipal);
            scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            MainPageTab.addTab("Contenido", scroll);
            
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al Intentar acceder a la Pagina: "+URL_Search.getText());
        }
    }//GEN-LAST:event_btnExecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ErrorConsole;
    private javax.swing.JTable ErrorTable;
    private javax.swing.JTabbedPane MainPageTab;
    private javax.swing.JTextField URL_Search;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExec;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
