/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author richard
 */
public class USAC_WEB_GUI extends javax.swing.JFrame {

    /**
     * Creates new form USAC_WEB_GUI
     */
    int index;
    public USAC_WEB_GUI() {
        initComponents();
        index = 0;
        Pestania p = new Pestania(web_tabs, index);
        web_tabs.add("Nueva", p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        web_tabs = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        add_tab = new javax.swing.JMenuItem();
        close_tab = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USAC WEB");

        web_tabs.setBackground(new java.awt.Color(255, 255, 255));
        web_tabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Opciones");

        add_tab.setText("Nueva Pestaña");
        add_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_tabActionPerformed(evt);
            }
        });
        jMenu1.add(add_tab);

        close_tab.setText("Cerrar Pestaña");
        close_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_tabActionPerformed(evt);
            }
        });
        jMenu1.add(close_tab);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(web_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(web_tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_tabActionPerformed
        // ADDS NEW TABS TO THE VIEW
        Pestania p = new Pestania(web_tabs, web_tabs.getSelectedIndex()+1);
        web_tabs.add("Nueva Pestania",p);
    }//GEN-LAST:event_add_tabActionPerformed

    private void close_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_tabActionPerformed
        // DELETS DE CURRENT TAB
        int closetab = web_tabs.getSelectedIndex();
        /*if(web_tabs.getTabCount()>1)
        {
            web_tabs.remove(closetab);
        }*/
        JPanel aux = (JPanel)web_tabs.getComponent(0);
        JPanel aux2 = (JPanel)aux.getComponent(0);
        JTextField s = (JTextField)aux2.getComponent(3);
        JOptionPane.showMessageDialog(null, s.getText());
    }//GEN-LAST:event_close_tabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USAC_WEB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USAC_WEB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USAC_WEB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USAC_WEB_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USAC_WEB_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add_tab;
    private javax.swing.JMenuItem close_tab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane web_tabs;
    // End of variables declaration//GEN-END:variables
}
