
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 27 13:25:57 CST 2018
//----------------------------------------------------

package CCSS;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tamtext = 36;
  public static final int opaque = 43;
  public static final int minus = 32;
  public static final int negrilla = 29;
  public static final int Tfalse = 7;
  public static final int Ttrue = 6;
  public static final int oBracket = 3;
  public static final int coma = 34;
  public static final int derecha = 21;
  public static final int igual = 25;
  public static final int identificador = 2;
  public static final int letra = 35;
  public static final int cBracket = 4;
  public static final int grupo = 16;
  public static final int alineado = 19;
  public static final int justificado = 22;
  public static final int vertical = 39;
  public static final int menos = 11;
  public static final int visible = 41;
  public static final int EOF = 0;
  public static final int cadena2 = 26;
  public static final int mas = 10;
  public static final int cp = 15;
  public static final int error = 1;
  public static final int capital = 33;
  public static final int pcoma = 18;
  public static final int entero = 8;
  public static final int horizontal = 38;
  public static final int mayus = 31;
  public static final int op = 14;
  public static final int por = 12;
  public static final int felemento = 37;
  public static final int id = 17;
  public static final int colortext = 44;
  public static final int centrado = 23;
  public static final int texto = 27;
  public static final int izquierda = 20;
  public static final int dosP = 24;
  public static final int formato = 28;
  public static final int borde = 42;
  public static final int div = 13;
  public static final int autoRed = 40;
  public static final int cursiva = 30;
  public static final int decimal = 9;
  public static final int cadena = 5;
}

